name: adlik
description: A smart offline-first education platform for Yemen and the world.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # إدارة الحالة
  provider: ^6.0.5

  # قاعدة بيانات محلية للـ Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # فتح ملفات PDF
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.3

  # ذكاء اصطناعي (الاتصال محلي/مستقبلاً)
  http: ^1.2.2

  # تخزين آمن إذا احتجناه لاحقاً
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.1.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/books/
    - assets/icons/
    - assets/images/
