name: Flutter CI - build apk & web

on:
  push:
    branches: [ feat/flutter-setup, main ]
  workflow_dispatch:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Build web
        working-directory: app
        run: flutter build web --release

      - name: Build APK (release)
        working-directory: app
        run: flutter build apk --release

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: adlukk-web
          path: app/build/web

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: adlukk-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
